# Site settings
title: Ferdi's Mind Palace
description: >-
  This blog is a media to express my passion in tech, coding, data science, and any other related topics, which may also serves as a personal notes and cheatsheet. My Mind Palace.
lang: fr-CA
timezone: Canada/Eastern
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/noxouille/blog 
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Ferdi Pratama
  bio: >-
    Azure Cloud Developer @CGI
  username: noxouille
  email: ferdi.pratama.phd@outlook.com
  avatar: /assets/img/avatar.webp

# Url settings
url: "https://ferdi.now.sh"
baseurl:
permalink: /:title/
google_analytics: UA-122702860-3
fb_appid:

# Collection setting
collections:
  badges:
    output: true
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles

incremental: true