# docker compose up -d && docker attach blog-jekyll-1
# docker compose down
version: "3.9"
services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
    command: jekyll serve --watch --incremental
